dispatcher:
  name: "default"
  concurrency_num: 2
datasets:
  - name: "data_classification_train"
    data: "demo/data_classification_train.json"
    prompt: "demo/prompt.yaml"
    prompt_type: "instruction"
    preprocess: "shuffle"
  - name: "data_generation_train"
    data: "demo/data_generation_train.json"
    prompt: "demo/prompt.yaml"
    prompt_type: "instruction"
    preprocess: "shuffle"
adapters:
  - name: "lora_classification"
    type: "lora"
    path: "adapters/lora_sft_0"
    optimizer: "adamw"
    lr: 2e-4
    r: 16
    alpha: 32
    dropout: 0.1
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: false
      gate_proj: false
      down_proj: false
      up_proj: false
  - name: "lora_generation"
    type: "lora"
    path: "adapters/lora_sft_1"
    optimizer: "adamw"
    lr: 5e-5
    r: 8
    alpha: 16
    dropout: 0.2
    target_modules:
      q_proj: true
      k_proj: false
      v_proj: true
      o_proj: false
      gate_proj: false
      down_proj: false
      up_proj: false
tasks:
  - type: "train"
    name: "task_classification"
    adapter: "lora_classification"
    dataset: "data_classification_train"
    batch_size: 8
    mini_batch_size: 4
    num_epochs: 2
    cutoff_len: 2048
    save_step: 50
    device_map: "auto"
  - type: "train"
    name: "task_generation"
    adapter: "lora_generation"
    dataset: "data_generation_train"
    batch_size: 8
    mini_batch_size: 4
    num_epochs: 2
    cutoff_len: 2048
    save_step: 50
    device_map: "auto"